Ext.define("skyfrog.view.masters.items.ItemsForm", {
  extend: "Ext.window.Window",
  xtype: "itemsform",

  bind: {
    title: "{title}",
  },
  listeners: {
    beforerender: "beforeDetailRender",
  },

  bodyPadding: 10,
  layout: "fit",
  modal: true,
  width: 500,
  height: undefined,
  closable: false,

  items: {
    xtype: "form",
    reference: "itemsform",
    bodyPadding: undefined,
    border: false,
    modelValidation: true,
    layout: {
      type: "vbox",
      align: "stretch",
    },
    checkboxToggle: true,
    defaultType: "checkbox",
    items: [
      {
        xtype: "textfield",
        fieldLabel: 'Code Item <span style="color: red">*</span>',
        reference: "code",
        itemId: "code",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: false,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Description',
        reference: "description",
        itemId: "description",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Width',
        reference: "width",
        itemId: "width",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Length',
        reference: "length",
        itemId: "length",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Height',
        reference: "height",
        itemId: "height",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Weight',
        reference: "weight",
        itemId: "weight",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "combobox",
        fieldLabel: "Item Type:",
        reference: "itemtype",
        itemId: "itemtype",
        queryMode: "local",
        publishes: "value",
        value: "Please Select Type",
        triggerAction: "all",
        forceSelection: true,
        editable: false,
        displayField: "name",
        valueField: "value",
        margin: "10 10 5 10",
        store: {
          fields: ["name", "value"],
          data: [
            {
              name: "Item General",
              value: "Item General",
            },
            { name: "ItemInw", value: "ItemInw" },
          ],
        },
      },
      {
        checked: true,
        margin: "0 10 5 10",
        fieldLabel: "Status:",
        boxLabel: "Actived",
        name: "status",
        inputValue: "actived",
      }
    ],
  },

  buttons: [
    {
      text: "Save",
      handler: "onCancelClick",
    },
    {
      text: "Cancel",
      handler: "onCancelClick",
    },
  ],
});
