Ext.define("skyfrog.view.masters.jobtype.JobTypeForm", {
  extend: "Ext.window.Window",
  xtype: "jobtypeform",

  bind: {
    title: "{title}",
  },

  bodyPadding: 10,
  layout: "fit",
  modal: true,
  width: 500,
  height: undefined,
  closable: false,

  listeners: {
    beforerender: "beforeDetailRender"
  },

  items: {
    xtype: "form",
    reference: "jobprefixform",
    bodyPadding: undefined,
    border: false,
    // use the Model's validations for displaying form errors
    modelValidation: true,
    layout: {
      type: "vbox",
      align: "stretch",
    },
    checkboxToggle: true,
    defaultType: "checkbox",
    items: [
      {
        xtype: "textfield",
        fieldLabel: 'Prefix <span style="color: red">*</span>',
        reference: "prefixfield",
        itemId: "prefix",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: false,
        msgTarget: "side",
        padding: undefined,
        margin: "10 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Description <span style="color: red">*</span>',
        reference: "description",
        itemId: "description",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: false,
        msgTarget: "side",
        padding: undefined,
        margin: "0 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'Owner',
        reference: "owner",
        itemId: "owner",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "0 10 5 10",
      },
      {
        xtype: "combobox",
        queryMode: "local",
        fieldLabel: "Type:",
        name: "type",
        itemId: "type",
        reference: "type",
        publishes: "value",
        value: "deliver",
        triggerAction: "all",
        forceSelection: true,
        editable: false,
        displayField: "name",
        valueField: "value",
        margin: "0 10 5 10",
        store: {
          fields: ["name", "value"],
          data: [
            { name: "Deliver", value: "deliver" },
            { name: "Return", value: "return" },
          ],
        },
      },
      {
        xtype: "textfield",
        fieldLabel: 'Loading Time:',
        reference: "loading",
        itemId: "loading",
        publishes: "value",
        value: "15",
        labelAsHtml: true,
        allowBlank: false,
        msgTarget: "side",
        padding: undefined,
        margin: "0 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'UnLoading Time',
        reference: "unloading",
        itemId: "unloading",
        publishes: "value",
        value: "15",
        labelAsHtml: true,
        allowBlank: false,
        msgTarget: "side",
        padding: undefined,
        margin: "0 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'MaxLoding Time:',
        reference: "maxloading",
        itemId: "maxloading",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "0 10 5 10",
      },
      {
        xtype: "textfield",
        fieldLabel: 'MaxUnLoding Time:',
        reference: "maxunloading",
        itemId: "maxunloading",
        publishes: "value",
        value: "",
        labelAsHtml: true,
        allowBlank: true,
        msgTarget: "side",
        padding: undefined,
        margin: "0 10 5 10",
      },
      {
        margin: "5 10 0 10",
        fieldLabel: "Default:",
        boxLabel: "Yes",
        name: "default",
        inputValue: "yes",
      },
      {
        checked: true,
        margin: "0 10 5 10",
        fieldLabel: "Status:",
        boxLabel: "Active",
        name: "status",
        inputValue: "active",
      },
    ],
  },

  buttons: [
    {
      text: "Save",
      handler: "onCancelClick",
    },
    {
      text: "Cancel",
      handler: "onCancelClick",
    },
  ],
});
